#ifndef ORYN_KERNEL_BOOT_INFO_H
#define ORYN_KERNEL_BOOT_INFO_H

#include "OrynBootInfo.h"
#include "OrynBootInfoSelection.h"

#ifndef ORYN_BOOTINFO_SELECTION_NUMBER
#define ORYN_BOOTINFO_SELECTION_NUMBER 0
#endif

#ifndef ORYN_BOOTINFO_SELECTION_NAME
#define ORYN_BOOTINFO_SELECTION_NAME "SDK default"
#endif

#ifndef ORYN_BOOTINFO_WANT_KERNEL_RANGE
#define ORYN_BOOTINFO_WANT_KERNEL_RANGE 1
#endif

#ifndef ORYN_BOOTINFO_WANT_MEMORY_MAP
#define ORYN_BOOTINFO_WANT_MEMORY_MAP 1
#endif

#ifndef ORYN_BOOTINFO_WANT_FRAMEBUFFER
#define ORYN_BOOTINFO_WANT_FRAMEBUFFER 1
#endif

#ifndef ORYN_BOOTINFO_WANT_RSDP
#define ORYN_BOOTINFO_WANT_RSDP 1
#endif

#ifndef ORYN_BOOTINFO_WANT_FIRMWARE_DATA
#define ORYN_BOOTINFO_WANT_FIRMWARE_DATA 1
#endif

#ifndef ORYN_BOOTINFO_WANT_PLATFORM_TABLES
#define ORYN_BOOTINFO_WANT_PLATFORM_TABLES ORYN_BOOTINFO_WANT_FIRMWARE_DATA
#endif

#ifndef ORYN_BOOTINFO_WANT_NVRAM
#define ORYN_BOOTINFO_WANT_NVRAM ORYN_BOOTINFO_WANT_FIRMWARE_DATA
#endif

#ifndef ORYN_BOOTINFO_WANT_RUNTIME_SERVICES
#define ORYN_BOOTINFO_WANT_RUNTIME_SERVICES ORYN_BOOTINFO_WANT_FIRMWARE_DATA
#endif

#ifndef ORYN_BOOTINFO_SELECTION_MASK
#define ORYN_BOOTINFO_SELECTION_MASK \
    ((ORYN_BOOTINFO_WANT_KERNEL_RANGE ? ORYN_BOOTINFO_FLAG_KERNEL_RANGE : 0ULL) | \
     (ORYN_BOOTINFO_WANT_MEMORY_MAP ? ORYN_BOOTINFO_FLAG_MEMORY_MAP : 0ULL) | \
     (ORYN_BOOTINFO_WANT_FRAMEBUFFER ? ORYN_BOOTINFO_FLAG_FRAMEBUFFER : 0ULL) | \
     (ORYN_BOOTINFO_WANT_RSDP ? ORYN_BOOTINFO_FLAG_RSDP : 0ULL) | \
     (ORYN_BOOTINFO_WANT_FIRMWARE_DATA ? ORYN_BOOTINFO_FLAG_FIRMWARE_DATA : 0ULL) | \
     (ORYN_BOOTINFO_WANT_PLATFORM_TABLES ? ORYN_BOOTINFO_FLAG_CONFIGURATION_TABLES : 0ULL) | \
     (ORYN_BOOTINFO_WANT_NVRAM ? ORYN_BOOTINFO_FLAG_NVRAM_SNAPSHOT : 0ULL) | \
     (ORYN_BOOTINFO_WANT_RUNTIME_SERVICES ? ORYN_BOOTINFO_FLAG_RUNTIME_SERVICES : 0ULL))
#endif

#define ORYN_KERNEL_BOOTINFO_KNOWN_FLAGS \
    (ORYN_BOOTINFO_FLAG_MEMORY_MAP | \
     ORYN_BOOTINFO_FLAG_FRAMEBUFFER | \
     ORYN_BOOTINFO_FLAG_RSDP | \
     ORYN_BOOTINFO_FLAG_KERNEL_RANGE | \
     ORYN_BOOTINFO_FLAG_FONT | \
     ORYN_BOOTINFO_FLAG_FIRMWARE_DATA | \
     ORYN_BOOTINFO_FLAG_CONFIGURATION_TABLES | \
     ORYN_BOOTINFO_FLAG_NVRAM_SNAPSHOT | \
     ORYN_BOOTINFO_FLAG_RUNTIME_SERVICES)

typedef struct OrynKernelBootInfoStatus
{
    int IsValid;
    int WarningCount;
} OrynKernelBootInfoStatus;

const OrynBootInfo* KernelBootInfoAdopt(const OrynBootInfo* bootInfo);
int KernelBootInfoIsKernelOwned(const OrynBootInfo* bootInfo);
unsigned long long KernelBootInfoSourceAddress(void);
OrynKernelBootInfoStatus KernelBootInfoValidate(const OrynBootInfo* bootInfo);
void KernelBootInfoPrintSelection(void);
void KernelBootInfoPrintSummary(const OrynBootInfo* bootInfo);
int KernelBootInfoHasFlag(const OrynBootInfo* bootInfo, unsigned long long flag);

#endif
