/* Low-memory AP startup trampoline for KernelSmp.c. */

__asm__(
".section .text.smptramp,\"ax\"\n"
".global OrynSmpTrampolineStart\n"
".global OrynSmpTrampolineEnd\n"
".global OrynSmpTrampolineGdt\n"
".global OrynSmpTrampolineGdtPointer\n"
".global OrynSmpTrampolineCr3\n"
".global OrynSmpTrampolineEntry\n"
".global OrynSmpTrampolineStackTop\n"
".global OrynSmpTrampolineApicId\n"
".code16\n"
"OrynSmpTrampolineStart:\n"
"    cli\n"
"    movw %cs, %ax\n"
"    movw %ax, %ds\n"
"    movw %ax, %es\n"
"    xorw %ax, %ax\n"
"    movw %ax, %ss\n"
"    movw $0x7000, %sp\n"
"    lgdtl OrynSmpTrampolineGdtPointer - OrynSmpTrampolineStart\n"
"    movl %cr0, %eax\n"
"    orl $0x1, %eax\n"
"    movl %eax, %cr0\n"
"    ljmpl $0x08, $(0x8000 + OrynSmpTrampolineProtected - OrynSmpTrampolineStart)\n"
".code32\n"
"OrynSmpTrampolineProtected:\n"
"    movw $0x10, %ax\n"
"    movw %ax, %ds\n"
"    movw %ax, %es\n"
"    movw %ax, %ss\n"
"    movl %cr4, %eax\n"
"    orl $0x20, %eax\n"
"    movl %eax, %cr4\n"
"    movl $0x8000, %esi\n"
"    movl OrynSmpTrampolineCr3 - OrynSmpTrampolineStart(%esi), %eax\n"
"    movl %eax, %cr3\n"
"    movl $0xC0000080, %ecx\n"
"    rdmsr\n"
"    orl $0x100, %eax\n"
"    wrmsr\n"
"    movl %cr0, %eax\n"
"    orl $0x80000000, %eax\n"
"    movl %eax, %cr0\n"
"    ljmpl $0x18, $(0x8000 + OrynSmpTrampolineLong - OrynSmpTrampolineStart)\n"
".code64\n"
"OrynSmpTrampolineLong:\n"
"    movw $0x20, %ax\n"
"    movw %ax, %ds\n"
"    movw %ax, %es\n"
"    movw %ax, %ss\n"
"    movq OrynSmpTrampolineStackTop - OrynSmpTrampolineStart(%rip), %rsp\n"
"    andq $~0xFULL, %rsp\n"
"    movl OrynSmpTrampolineApicId - OrynSmpTrampolineStart(%rip), %edi\n"
"    movq OrynSmpTrampolineEntry - OrynSmpTrampolineStart(%rip), %rax\n"
"    call *%rax\n"
"1: hlt\n"
"    jmp 1b\n"
".align 16\n"
"OrynSmpTrampolineGdt:\n"
"    .quad 0x0000000000000000\n"
"    .quad 0x00CF9A000000FFFF\n"
"    .quad 0x00CF92000000FFFF\n"
"    .quad 0x00AF9A000000FFFF\n"
"    .quad 0x00CF92000000FFFF\n"
"OrynSmpTrampolineGdtPointer:\n"
"    .word 0x27\n"
"    .long 0\n"
"OrynSmpTrampolineCr3:\n"
"    .quad 0\n"
"OrynSmpTrampolineEntry:\n"
"    .quad 0\n"
"OrynSmpTrampolineStackTop:\n"
"    .quad 0\n"
"OrynSmpTrampolineApicId:\n"
"    .long 0\n"
"OrynSmpTrampolineEnd:\n"
".text\n"
".code64\n"
);

