Order=14
Id=OrynKernelModulePci
Name=PCI
Items=bus scan, config space, class decode, MSI, MSI-X, device interrupt records, AHCI/SATA driver binding
Requires=OrynKernelModuleBootInfo
CompiledIn=Yes
Required=No
FatalOnMissingPrerequisite=No
Select=BootInfoRsdp

StopCallback=OrynKernelModuleDefaultStop
PanicCallback=OrynKernelModuleDefaultPanic
ShutdownCallback=OrynKernelModuleDefaultShutdown
