Order=19
Id=OrynKernelModulePhysicalMemory
Name=PhysicalMemory
Items=usable pages, free list, allocation proof, DMA-safe constraints, contiguous constrained allocations
Requires=OrynKernelModuleBootInfo
CompiledIn=Yes
Required=No
FatalOnMissingPrerequisite=Yes
Select=BootInfoMemoryMap

StopCallback=OrynKernelModuleDefaultStop
PanicCallback=OrynKernelModuleDefaultPanic
ShutdownCallback=OrynKernelModuleDefaultShutdown
