
Order=22
Id=OrynKernelModuleProcess
Name=Process
Items=process structures, per-process address spaces, ownership, lifecycle state
Requires=OrynKernelModuleVirtualMemory
CompiledIn=Yes
Required=No
FatalOnMissingPrerequisite=Yes
Select=BootInfoMemoryMap,BootInfoKernelRange

StopCallback=OrynKernelModuleDefaultStop
PanicCallback=OrynKernelModuleDefaultPanic
ShutdownCallback=OrynKernelModuleDefaultShutdown
