
Order=23
Id=OrynKernelModuleScheduler
Name=Scheduler
Items=kernel thread records, scheduler-ready stacks, guarded stack allocation, timer wheel, sleep queues, work queues, wait queues
Requires=OrynKernelModuleProcess,OrynKernelModuleHeap
CompiledIn=Yes
Required=No
FatalOnMissingPrerequisite=Yes
Select=BootInfoMemoryMap,BootInfoKernelRange

StopCallback=OrynKernelModuleDefaultStop
PanicCallback=OrynKernelModuleDefaultPanic
ShutdownCallback=OrynKernelModuleDefaultShutdown
