
Order=23
Id=OrynKernelModuleScheduler
Name=Scheduler
Items=kernel thread records, scheduler-ready stacks, guarded stack allocation, timer wheel, sleep queues, work queues, wait queues, per-CPU run queues, pre-emptive round-robin scheduler
Requires=OrynKernelModuleProcess,OrynKernelModuleHeap
CompiledIn=Yes
Required=No
FatalOnMissingPrerequisite=Yes
Select=BootInfoMemoryMap,BootInfoKernelRange

StopCallback=OrynKernelModuleDefaultStop
PanicCallback=OrynKernelModuleDefaultPanic
ShutdownCallback=OrynKernelModuleDefaultShutdown
