
Order=23
Id=OrynKernelModuleScheduler
Name=Scheduler
Items=priorities, thread states, wait/wake primitives, per-CPU idle thread registration, kernel thread records, scheduler-ready stacks, guarded stack allocation, timer wheel, sleep queues, work queues, wait queues, per-CPU run queues, pre-emptive round-robin scheduler, CPU affinity, scheduler diagnostics, run-queue dumps
Requires=OrynKernelModuleProcess,OrynKernelModuleHeap
CompiledIn=Yes
Required=No
FatalOnMissingPrerequisite=Yes
Select=BootInfoMemoryMap,BootInfoKernelRange

StopCallback=OrynKernelModuleDefaultStop
PanicCallback=OrynKernelModuleDefaultPanic
ShutdownCallback=OrynKernelModuleDefaultShutdown
