#ifndef ORYN_BOOT_INFO_SELECTION_H
#define ORYN_BOOT_INFO_SELECTION_H

#define ORYN_BOOTINFO_SELECTION_NUMBER 0
#define ORYN_BOOTINFO_SELECTION_NAME "UEFI x64 SDK default"
#define ORYN_BOOTINFO_SELECTION_MASK 0x1EF

#define ORYN_BOOTINFO_WANT_KERNEL_RANGE 1
#define ORYN_BOOTINFO_WANT_MEMORY_MAP 1
#define ORYN_BOOTINFO_WANT_FRAMEBUFFER 1
#define ORYN_BOOTINFO_WANT_RSDP 1
#define ORYN_BOOTINFO_WANT_FIRMWARE_DATA 1
#define ORYN_BOOTINFO_WANT_PLATFORM_TABLES 1
#define ORYN_BOOTINFO_WANT_NVRAM 1
#define ORYN_BOOTINFO_WANT_RUNTIME_SERVICES 1

#endif
