#ifndef ORYN_BOOT_TARGET_H
#define ORYN_BOOT_TARGET_H

#define ORYN_BOOT_TARGET_KERNEL_NAME "Kernel"
#define ORYN_BOOT_TARGET_TARGET_NAME "uefi-x64"
#define ORYN_BOOT_TARGET_TOOLCHAIN_NAME "clang"
#define ORYN_BOOT_TARGET_ARCHITECTURE_NAME "x86_64"
#define ORYN_BOOT_TARGET_KERNEL_COMMAND_LINE ""
#define ORYN_BOOT_TARGET_KERNEL_DIRECTORY "KERNEL"
#define ORYN_BOOT_TARGET_KERNEL_HOST_FILE "Kernel.elf"
#define ORYN_BOOT_TARGET_KERNEL_FILE "KERNEL.elf"
#define ORYN_BOOT_TARGET_KERNEL_PATH_TEXT "\\System\\KERNEL\\KERNEL.elf"
#define ORYN_BOOT_TARGET_KERNEL_PATH L"\\System\\KERNEL\\KERNEL.elf"

#endif
